name: Enhancement
description: Suggest improvements or refinements to an existing feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide details on how this enhancement will improve the project.
  - type: textarea
    id: description
    attributes:
      label: Describe the enhancement
      placeholder: The current feature X could be improved by doing Y.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Why should this enhancement be implemented? Add additional informaiton.
      placeholder: This improvement will help users by allowing Z.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have searched for similar issues before creating this one.
        - label: I have provided all the necessary information to understand this documentation issue.